package model

// State machine definitions. Every entity carries a status field whose legal
// transitions are validated by the CanTransition helpers below.

// Batch states: a SAR imaging batch travels from reception through diagnosis
// review to confirmation and finally archival.
const (
	BatchReceiving = "receiving"         // 接收中
	BatchPending   = "pending_diagnosis" // 待诊断
	BatchReview    = "needs_review"      // 需复核
	BatchConfirmed = "confirmed"         // 已确认
	BatchArchived  = "archived"          // 封存
)

// BatchTransitions maps current state -> set of allowed next states.
var BatchTransitions = map[string]map[string]bool{
	BatchReceiving: {BatchPending: true},
	BatchPending:   {BatchReview: true, BatchConfirmed: true, BatchReceiving: true},
	BatchReview:    {BatchConfirmed: true, BatchPending: true},
	BatchConfirmed: {BatchArchived: true, BatchReview: true},
	BatchArchived:  {}, // terminal
}

// Peak region states: raw regions become analysis candidates and are then
// resolved into sidelobe / strong scatter / excluded conclusions.
const (
	PeakRaw       = "raw"       // 原始
	PeakCandidate = "candidate" // 候选
	PeakSidelobe  = "sidelobe"  // 旁瓣
	PeakScatter   = "scatter"   // 强散射
	PeakExcluded  = "excluded"  // 排除
)

// PeakTransitions maps peak region state -> allowed next states.
var PeakTransitions = map[string]map[string]bool{
	PeakRaw:       {PeakCandidate: true, PeakScatter: true, PeakExcluded: true},
	PeakCandidate: {PeakSidelobe: true, PeakScatter: true, PeakExcluded: true},
	PeakSidelobe:  {},
	PeakScatter:   {PeakExcluded: true},
	PeakExcluded:  {},
}

// Candidate states: contamination candidates are generated by analysis and
// reviewed by engineers.
const (
	CandGenerated    = "generated"    // 生成
	CandInsufficient = "insufficient" // 证据不足
	CandConfirmed    = "confirmed"    // 确认
	CandRejected     = "rejected"     // 否决
)

// CandidateTransitions maps candidate state -> allowed next states.
var CandidateTransitions = map[string]map[string]bool{
	CandGenerated:    {CandInsufficient: true, CandConfirmed: true, CandRejected: true},
	CandInsufficient: {CandConfirmed: true, CandRejected: true, CandGenerated: true},
	CandConfirmed:    {CandRejected: true},
	CandRejected:     {CandConfirmed: true},
}

// Snapshot states: diagnosis snapshots are drafts that get published and may
// later be superseded by a newer version.
const (
	SnapDraft      = "draft"      // 草稿
	SnapPublished  = "published"  // 发布
	SnapSuperseded = "superseded" // 替代
)

// SnapshotTransitions maps snapshot state -> allowed next states.
var SnapshotTransitions = map[string]map[string]bool{
	SnapDraft:      {SnapPublished: true},
	SnapPublished:  {SnapSuperseded: true},
	SnapSuperseded: {},
}

// Analysis run states.
const (
	RunPending  = "pending"  // 排队中
	RunRunning  = "running"  // 运行中
	RunFinished = "finished" // 完成
	RunFailed   = "failed"   // 失败
)

// CanTransition reports whether from -> to is legal for the batch machine.
func CanBatchTransition(from, to string) bool {
	return BatchTransitions[from][to]
}

// CanPeakTransition reports whether from -> to is legal for peak regions.
func CanPeakTransition(from, to string) bool {
	return PeakTransitions[from][to]
}

// CanCandidateTransition reports whether from -> to is legal for candidates.
func CanCandidateTransition(from, to string) bool {
	return CandidateTransitions[from][to]
}

// CanSnapshotTransition reports whether from -> to is legal for snapshots.
func CanSnapshotTransition(from, to string) bool {
	return SnapshotTransitions[from][to]
}

// IsBatchImmutable reports whether the batch can no longer accept persisted
// diagnosis artifacts.
func IsBatchImmutable(status string) bool {
	return status == BatchArchived
}

// CanPublishSnapshot reports whether diagnosis review has completed.
func CanPublishSnapshot(status string) bool {
	return status == BatchConfirmed
}

// CanRegisterAnalysisInput reports whether raw peak inputs may still be
// appended before analysis has entered review.
func CanRegisterAnalysisInput(status string) bool {
	return true
}

// CanUpdateImagingParams reports whether acquisition geometry is still mutable
// before analysis has produced reviewable findings.
func CanUpdateImagingParams(status string) bool {
	return status == BatchReceiving || status == BatchPending
}
